[44기 김민서][ADD]search product
wecode-bootcamp-korea/44-1st-unicon-backend pull request #12
Opened 2023-04-11 02:17 UTC by minseoya

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 검색기능에 필요한 api

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- API 호출 시 프론트 단에서 필요한 정보 보내줌

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
4. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지

<br />

## :: 기타 질문 및 특이 사항
- 
<img width="760" alt="image" src="https://user-images.githubusercontent.com/119482288/231038235-d7cf7367-741d-4204-8c5d-cb233b154f06.png">

2023-04-11 05:27 UTC, kyeongraekim requested changes

2023-04-11 05:27 UTC, kyeongraekim commented on models/productDao.js
> +        JOIN  (SELECT product_id, JSON_ARRAYAGG(image_url) AS image_url FROM product_image GROUP BY product_id) AS image
- 가독성을 위해 전체적으로 라인브레이킹을 한 번 고민해보세요! 
```suggestion
        JOIN  (
            SELECT product_id, 
            JSON_ARRAYAGG(image_url) AS image_url 
            FROM product_image 
            GROUP BY product_id 
        )  AS image
```

2023-04-11 05:27 UTC, kyeongraekim commented on models/productDao.js
> +const searchProduct = async () => {
- 제품을 검색하는 내용인데 인자값이 아무것도 들어오지 않아도 되는 기획인가요? 한 번 고민해주신 내용을 이곳에 작성해주세요!~

2023-04-11 07:32 UTC, kyeongraekim requested changes

2023-04-11 07:32 UTC, kyeongraekim commented on models/productDao.js
> +    main_category.title LIKE "%${word}%"`
- 해당 부분도 기존에 작성해주신 쿼리빌더를 활용해볼 수 있겠네요!

2023-04-11 07:32 UTC, kyeongraekim commented on controllers/productController.js
> +  const word = req.params;
- 키워드를 params로 받는 이유가 별도로 있으실까요? query로 받아야 더 올바른 키워드를 인자로 받아서 사용가능할 것 같습니다~

2023-04-12 01:05 UTC, kyeongraekim requested changes

2023-04-12 01:05 UTC, kyeongraekim commented on controllers/productController.js
> +  console.log(word);
- 불필요한 콘솔로깅을 삭제해주세요!

2023-04-12 01:05 UTC, kyeongraekim commented on controllers/productController.js
> +  const { word } = req.body;
- 단일 키워드의 전달을 위해서 post & body를 사용하실 필요는 없어보이십니다.
- req.query를 사용하는게 더 보편적인 방법임을 다시 한 번 리뷰로 남겨드립니다.

2023-04-12 01:05 UTC, kyeongraekim commented on controllers/productController.js
> +  const { word } = req.body;
- 현재 프론트와의 기획에서 변경불가한 부분이시라면, 다음 프로젝트에서는 req.query 를 이용해서 get 요청 정보에 맞는 restful 한 엔드포인트를 설정해주세요!

2023-04-12 04:27 UTC, minseoya commented on controllers/productController.js
> +  const { word } = req.body;
넵 다음 프로젝트때 적용하도록 하겠습니다

2023-04-12 09:57 UTC, closed without merging