[임성근] [ADD] : Payment 기능 추가
wecode-bootcamp-korea/44-1st-unicon-backend pull request #13
Opened 2023-04-11 06:14 UTC by lsg622

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [x] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 유니콘 프로젝트 결제 기능 추가

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- 주문 번호를 통한 결재 확인 기능 구현

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
4. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지

<br />

## :: 기타 질문 및 특이 사항
- 제가 작성한 함수의 로직이 너무 복잡하다고 생각이 됩니다. 더 효율적인 방법이 없을까요? (예시)

2023-04-11 08:22 UTC, kyeongraekim requested changes

2023-04-11 08:22 UTC, kyeongraekim commented on models/paymentDao.js
> +const createPayment = async (orderNumber) => {
- 해당 내용은 결제가 이루어지는 로직이기 때문에 transaction 이 전체적으로 걸려있어야 될 것 같습니다!~

2023-04-11 08:22 UTC, kyeongraekim commented on models/paymentDao.js
> +    );
- 또한 마지막 로직은 결제가 이루어진 이후의 상황이니 기존 유저의 Point에서 해당 가격만큼 차감이 이루어지는 로직까지 마지막에 이루어져야 되겠네요!

2023-04-13 03:09 UTC, lsg622 commented
멘토님! conflict 내역은 추후 메인에 다른 선행 파일이 merge 된 이후 해결하는 식으로 팀원과 의논하였습니다!!

2023-04-13 08:12 UTC, closed without merging