[임성근][ADD]: 회원가입, 로그인, 인가 통합 기능 구현
wecode-bootcamp-korea/44-1st-unicon-backend pull request #5
Opened 2023-04-05 09:17 UTC by lsg622

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 회원가입, 로그인, 인가 통합 기능 구현

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- API 호출 시  회원가입(password bcrypt 적용), 로그인 기능(token 생성) 구현 완성.
-  인가 과정은 현재 프로젝트 진행상 어떤 기능에서 인가과정을 진행할 것인지 정해진 것이 없기에, 인가 기능 기본 틀만 작성였습니다.
-  추후, 진행되는 프로젝트 일정에 따라 인가 기능을 구체적으로 추가할 예정입니다.

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
4. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지

<br />

## :: 기타 질문 및 특이 사항
- 제가 작성한 함수의 로직이 너무 복잡하다고 생각이 됩니다. 더 효율적인 방법이 없을까요? (예시)

2023-04-05 12:02 UTC, kyeongraekim requested changes

2023-04-05 12:02 UTC, kyeongraekim commented on .env
> +SECRET_KEY = 'mySercetKey'
- 절대 올라와서는 안되는 개인 .env 파일이 올라와있네요! 해당 내용 수정 부탁드립니다!

2023-04-05 12:02 UTC, kyeongraekim commented on controllers/userController.js
> +  return res.status(201).json({ accesstoken: Token });
- signIn 로그인에 해당되는 상태코드인 200으로 상태코드를 수정해주세요!

2023-04-05 12:02 UTC, kyeongraekim commented on middlewares/auth.js
> +};
다음과 같이 수정해보는 것은 어떨까요?

```suggestion

const loginRequired = async (req, res, next) => {

	// 1) Getting token and check of it's there
  const accessToken = req.headers.authorization

	if (!accessToken) {
		const error = new Error('NEED_ACCESS_TOKEN')
		error.statusCode = 401
		
		return res.status(error.statusCode).json({message: error.message})
	}

  // 2) Verification token
  const decoded = await jwt.verify(accessToken, process.env.JWT_SECRET);

  // 3) Check if user still exists
	const user = await userService.getUserById(decoded.id)

	if (!user) {
		const error = new Error('USER_DOES_NOT_EXIST')
		error.statusCode = 404
		
		return res.status(error.statusCode).json({message: error.message})
	}

  // 4) GRANT ACCESS
  req.user = user;
  next();
}

module.exports = { loginRequired }
```

2023-04-05 12:02 UTC, kyeongraekim commented on middlewares/auth.js
> +  return validateToken;
- 미들웨어는 중간을 스쳐가는 코드임으로 필연적으로 무언가를 return하실 필요는 없습니다. 해당 인가코드의 중요한 내용은 6번에서 작성해주신 req 객체에 user라는 key에 id value 값을 넣어서, 다른 코드에서 언제든지 활용가능한 모습을 보이는것 입니다.

2023-04-05 12:02 UTC, kyeongraekim commented on models/userDao.js
> +		    names,
- 이곳 들여쓰기 한 번 신경써주세요!~

2023-04-05 12:02 UTC, kyeongraekim commented on models/userDao.js
> +		  ) VALUES (?, ?, ?, ?, ?, ?, 5000);
- 현재 points 가 하드코딩 되어 있는 것으로 보입니다. DEFAULT_POINTS와 같은 상수값을 담을 변수에 선언해서 따로 유지보수관리가 편하게 수정해주세요!

2023-04-05 12:02 UTC, kyeongraekim commented on models/userDao.js
> +         id
- pk 값인 id 값을 select 시 가장 먼저 호출해주세요!

2023-04-05 12:02 UTC, kyeongraekim commented on routes/index.js
> +const { validateToken } = require('../middlewares/auth');
- 이곳에서 valideToken의 쓰임이 확인되지는 않아보이네요!

2023-04-05 12:02 UTC, kyeongraekim commented on services/userService.js
> +// 회원가입 구현
- 코드 독해로 의미파악이 가능한 주석처리 내용은 삭제해주세요!

2023-04-05 12:02 UTC, kyeongraekim commented on services/userService.js
> +// 로그인 구현
- 코드 독해로 의미파악이 가능한 주석처리 내용은 삭제해주세요!

2023-04-05 14:08 UTC, lsg622 commented
요청하신 수정사항 중 들여쓰기는 자동으로 prettier가 작동하여 수정하여도 적용이 되지 않습니다. validateToken(loginrequired)의 쓰임 유무는  현재 프로젝트 진행상 어떤 기능에서 인가과정을 진행할 것인지 정해진 것이 없기에, 인가 기능 기본 틀만 작성하였습니다. 추후, 진행되는 프로젝트 일정에 따라 인가 기능을 구체적으로 추가할 예정입니다. 그 외 다른 수정사항은 전부 적용하여 push 하였습니다~

2023-04-06 06:08 UTC, kyeongraekim approved these changes
LGTM!~

2023-04-06 06:46 UTC, merged