Feat/cart
wecode-bootcamp-korea/44-1st-unicon-backend pull request #6
Opened 2023-04-06 05:20 UTC by Dongrang072

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 카트 구현

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- 카트 crud

sample: 
![스크린샷(76)](https://user-images.githubusercontent.com/52373572/230278768-6f6b0641-e61b-4808-848b-60aa77a27694.png)
![스크린샷(77)](https://user-images.githubusercontent.com/52373572/230278772-961a3659-a533-4f18-8c55-06904a05b520.png)

## :: 기타 질문 및 특이 사항

2023-04-06 06:11 UTC, kyeongraekim requested changes

2023-04-06 06:11 UTC, kyeongraekim commented on controllers/cartController.js
> +  //cart를 만들고 나서 carItem을 만들기
- 불필요한 주석을 삭제해주세요!~

2023-04-06 06:11 UTC, kyeongraekim commented on controllers/cartController.js
> +    console.log(1);
- 상용화될 코드인 main으로의 푸시에는 불필요한 콘솔로깅을 일괄 삭제해주신 후에 푸시해주셔야 합니다. 해당 내역을 삭제해주세요!

2023-04-06 06:11 UTC, kyeongraekim commented on controllers/cartController.js
> +  const update = await cartService.updateCart({userId, productId, quantity});
- updatedCart 정도가 더 의미적으로 맞는 변수명이겠네요!

2023-04-06 06:11 UTC, kyeongraekim commented on middlewares/authorize.js
> +module.exports = { authorize }
- 해당 내용은 성근님 코드에 반영이 되어 있습니다. 삭제해주셔도 될 코드로 보여지내요!~

2023-04-06 06:11 UTC, kyeongraekim commented on middlewares/bcrypt.js
> +  checkHash
- 해당내용도 성근님 코드에 반영이 되어있네요!

2023-04-06 06:11 UTC, kyeongraekim commented on models/cartDao.js
> +      //json
- 불필요한 코드 주석을 삭제해주세요!

2023-04-06 06:11 UTC, kyeongraekim commented on models/cartDao.js
> +    console.log('product: ' + product);
불필요한 코드 주석을 삭제해주세요!

2023-04-06 06:11 UTC, kyeongraekim commented on models/cartDao.js
> +    console.log('item: ' + item[0]);
불필요한 코드 주석을 삭제해주세요!

2023-04-06 06:47 UTC, kyeongraekim requested changes

2023-04-06 06:47 UTC, kyeongraekim commented on models/cartDao.js
> +const createCartItem = async ({ userId, productId, quantity }) => {
- 전체 카트에 대한 리뷰는 자리에서 구두로 드리겠습니다~ 곧 찾아뵐게요!

2023-04-07 09:49 UTC, Jon9Beom reviewed
전반적으로 중복되는 맥락의 리뷰나 수정 사항이 많아, 나눠서 우선 1차적으로 코멘트 남겨드리겠습니다! 반영 부탁드릴게요~!

2023-04-07 09:49 UTC, Jon9Beom commented on routes/index.js
> +const cartRouter = require("./cartRouter")
```suggestion
const express = require('express');

const cartRouter = require("./cartRouter")

const router = express.Router();
```
필요한 모듈을 불러온 뒤, 이를 활용하는 코드를 작성하는 순서가 일반적입니다.

2023-04-07 09:49 UTC, Jon9Beom commented on routes/index.js
> +//const orderRouter = require("./orderRouter")
```suggestion
```
주석 처리된 코드는 지워서 올라올 수 있게 해주세요.

2023-04-07 09:49 UTC, Jon9Beom commented on routes/index.js
>  const { loginRequired } = require('../middlewares/auth');
```suggestion
```
엔드포인트별 1차적인 분기라고도 생각할 수 있는 index.js에서는 loginRequired가 필요없습니다. 각각의 someRouter.js(가칭) 에서 필요한 엔드포인트 별로 사용될 것 이므로 해당 코드는 없어도 되겠습니다.

2023-04-07 09:49 UTC, Jon9Beom commented on routes/cartRouter.js
> +const { loginRequired } = require("../middlewares/auth");
```suggestion
const express = require("express");

const cartController = require("../controllers/cartController");
const { loginRequired } = require("../middlewares/auth");
```
외부 모듈, 커스텀 모듈간 구분을 위해 줄바꿈을 주면 보다 가독성 좋은 코드가 될 것 같습니다.

2023-04-07 09:49 UTC, Jon9Beom commented on controllers/cartController.js
> +});
```suggestion
const createCartItem = catchError(async (req, res) => {
  try {
    const { productId, quantity } = req.body;

    const userId = req.user.id;

    const cartItem = await cartService.createCartItem({
      userId,
      productId,
      quantity,
    });
    res.status(201).json({ message: cartItem });
  } catch (err) {
    res.status(400).json({ message: err.message });
  }
});
```
catchError 라는 에러핸들링에 관한 함수의 코드를 보면, 해당 함수의 인자로 들어가는 함수, 즉 controller 함수에는 try catch가 굳이 필요하지 않습니다.

2023-04-07 09:49 UTC, Jon9Beom commented on controllers/cartController.js
> +    res.status(201).json({ cartList });
```suggestion
    res.status(200).json({ cartList });
```
http request method 중 GET 과 관련된 더 적합한 status code를 사용할 수 있도록 해주세요.

2023-04-07 09:49 UTC, Jon9Beom commented on controllers/cartController.js
> +    res.status(201).json({ message: deleteCart });
```suggestion
    res.status(204).send();
```
위에서 언급드린 코멘트와 마찬가지로 삭제(DELETE) 메소드와 더 적합한 status code가 있습니다. 이를 활용하여 주시고 204는 클라이언트에서 바디를 받을 수 없기 때문에 따로 메세지를 담지 않고 위처럼 .send() 메소드를 통해 response를 보내주기만 해도 됩니다.

2023-04-07 09:49 UTC, Jon9Beom commented on models/myDataSources.js
> +module.exports = appDataSource;
기존 appDataSource.js와 중복이므로 해당파일은 지워주세요.

2023-04-10 04:09 UTC, kyeongraekim requested changes

2023-04-10 04:09 UTC, kyeongraekim commented on middlewares/bcrypt.js
> +  checkHash
- 이 부분의 middleware는 삭제해야되지 않을까요? 한 번 만 다시 판단해주세요!

2023-04-11 01:01 UTC, kyeongraekim requested changes

2023-04-11 01:01 UTC, kyeongraekim commented on controllers/productController.js
> +>>>>>>> origin
- 이곳 컨플릭트가 잘못 남아있네요! 수기로 삭제해주세요!

2023-04-11 05:28 UTC, kyeongraekim approved these changes

2023-04-11 05:28 UTC, merged