[김민서][ADD]Feature/product list
wecode-bootcamp-korea/44-1st-unicon-backend pull request #7
Opened 2023-04-06 06:57 UTC by minseoya

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 제품 리스트 페이지 가격필터, 카테고리로 들어가서도 가격필터 적용가능

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- 제품 리스트 페이지 가격필터, 카테고리로 들어가서도 가격필터 적용가능

<br />

## :: 테스트 결과 이미지
제품 리스트
![image](https://user-images.githubusercontent.com/119482288/230295499-88f710b0-5182-49dd-a4cf-7db05f84fa30.png)

<img width="711" alt="image" src="https://user-images.githubusercontent.com/119482288/230295670-50e0fd35-349c-49d9-abf8-f671457f6c8f.png">

<br />

## :: 기타 질문 및 특이 사항
-

2023-04-07 07:10 UTC, Kang-kyunghun requested changes

2023-04-07 07:10 UTC, Kang-kyunghun commented on controllers/productController.js
> +  }
1. if 시작 전 공백 추가해 주세요.
2. 데이터가 없을 때는 404 상태코드를 사용합니다.
3. 메시지가 명확한 것 같지 않아 아래와 같이 수정해 봤습니다.
```suggestion
  
  if (!productId) {
    return new baseError('PRODUCT_DOES_NOT_EXIST', 404);
  }
```

2023-04-07 07:10 UTC, Kang-kyunghun commented on controllers/productController.js
> +  const { mc, sc, pf, start = 0, count = 15, isnew } = req.query;
mc, sc 같이 불명확한 변수 사용은 자제해 주세요. 같이 작업하는 사람이 변수명만 보고도 어떤 값인지 알 수 있도록 변수명 수정해 주세요.

2023-04-07 07:10 UTC, Kang-kyunghun commented on models/productDao.js
> +    let order = '';
정렬에 대한 기본 default 값을 가질 수 있도록 수정해 주세요.

2023-04-07 07:10 UTC, Kang-kyunghun commented on models/productDao.js
> +      [count, start]
count, start 보다는 limit, offset으로 변수명을 바꾸어 어떤 값을 의미하는지 명확하게 해주세요.
```suggestion
      [limit, offset]
```

2023-04-07 07:10 UTC, Kang-kyunghun commented on controllers/productController.js
> +const categoryPage = catchError(async (req, res) => {
해당 API는 category page에서만 쓰이는 것이 아닐 수 있습니다. 어디서든 가져다가 쓸수 있기 때문에 API의 함수명을 지을 때는 page가 아닌 데이터 중심으로 보셔야 합니다.
해당 API는 제품 목록을 가져오는 API 이므로 다음과 같이 함수 명을 수정해 주세요.
```suggestion
const getProductList = catchError(async (req, res) => {
```

2023-04-07 07:10 UTC, Kang-kyunghun commented on models/productDao.js
> +    }
sc랑 mc가 동시에 있으면 sc는 무시되는거 아닌가요?
필터링 sql을 만드는 순서를 전체 필요한 조건문을 만들고 마지막에 WHERE을 붙이는 방법으로 한 번 바꿔보세요.

2023-04-07 09:52 UTC, kyeongraekim requested changes

2023-04-07 09:52 UTC, kyeongraekim commented on controllers/productController.js
> +    limit = 0,
- 15와 0 이라는 정수값을 DEFAULT_LIMIT, DEFAULT_OFFSET 과 같이 상수변수에 넣어서 관리해주세요! 해당 내용은 코드내 값이 하드코딩 되어 있는 내용이라고 보시면 됩니다. 웹 개발에서는 하드코딩을 최대한 지양해주셔야 합니다.

2023-04-07 09:52 UTC, kyeongraekim commented on controllers/productController.js
> +    limit = 0,
- 현재 sql 에 전달되는 변수명의 형태가 기본으로 설정해야하는 offset limit 이 아닌 start limit으로 설정되어 있네요! 해당 내용을 offset limit의 기본 네이밍 컨벤션에 통일시켜 설정해주세요!

2023-04-07 09:52 UTC, kyeongraekim commented on models/productDao.js
> +      [start, limit]
- 위에서 언급해드린 내용에 해당되는 곳 입니다!

2023-04-07 09:52 UTC, kyeongraekim commented on models/productDao.js
> +      p.id,
- 해당내용을 [productDetail] 과 같이 변수에 담아서 관리하는 것은 어떨까요? 추후 객체로서 접근하기 용이하고, 가독성, 유지보수성이 올라가는 효과를 줄 수 있습니다.

2023-04-07 09:52 UTC, kyeongraekim commented on models/productDao.js
> +    }
- 해당 내용을 올바른 기획으로 잘 작성해주셨는데 필터 요소의 조건이 추가될 때마다  매 새로운 경우의 조건절이 불필요하게 양산되는 문제점을 지니고 있습니다. 해당 내용은 모델 예시와 함께 구두로 관련 가이드를 전달드릴 수 있도록 하겠습니다!

2023-04-10 04:08 UTC, kyeongraekim approved these changes
LGTM!~

2023-04-10 04:08 UTC, merged